#' Plot Stacked Bar Plots explaining k-means clustering and Fisher's Exact test
#'
#' @param selected_data     Returned list from the \code{\link{stim_cell_selector}} function.
#' @param path              Path to the folder to save figures generated by this function.
#' @param verbose           Logical. To make function more verbose. Default is FALSE.
#'
#' @return This function generates figures in the specified path folder and returns 0.
#' @export
plot_sbp <- function(selected_data, path, verbose = FALSE){
  # Check if path exists; if not then create it.
  if(!is.null(path)){
    if(!dir.exists(path)){
      if(verbose){message(paste("Creating %s folder", path))}
      dir.create(path, recursive = TRUE)
    } else {
      if(verbose){message(paste(path, "folder already exists. Output will be over written."))}
    }
  }

  # Bind global variables.
  cluster <- k_cluster <- stim_status <- stim_type <- NULL

  # Group data according to clusters and stimulation type.
  group_data <- group_by(selected_data$stacked_bar_plot_data, cluster, stim_type)

  # Split groups into a list of individual tables.
  split_groups <- group_split(group_data)

  # Create ggplot for a single group.
  for(i in 1:length(split_groups)){
    clust <- unique(split_groups[[i]]$cluster)
    stim <- unique(split_groups[[i]]$stim_type)
    if(verbose){message(paste("Plotting for the cluster", clust, "and the stim type", stim))}
    stacked_plot <- ggplot(split_groups[[i]], aes(fill = k_cluster, y=count, x=stim_status)) +
      geom_bar(position="fill", stat="identity") +
      labs(title=paste("Cluster:", clust,
                       "; Stim type:", stim,
                       "\nFisher's p-value:", round(unique(split_groups[[i]]$f_p_val),3),
                       "; Stim cluster:",unique(split_groups[[i]]$stim_clust),
                       "; Fold change:", unique(split_groups[[i]]$fold_change) ,  sep=" "),
           x ="Stim Status", y = "Cell Count %", fill = "K-means Cluster")

    if(!is.null(path)){
      ggsave(paste0("plot_sbp_",clust,"_", stim, ".png"),
             plot = stacked_plot, device = "png", path = file.path(path), width = 6, height = 4, dpi = 300)
    }
  }
  return(0)
}


#' Plot UMAPs for the Selected Cells
#'
#' @param selected_data      Returned list from the \code{\link{stim_cell_selector}} function.
#' @param path               Path to the folder to save figures generated by this function.
#' @param verbose            Logical. To make function more verbose. Default is FALSE.
#'
#' @return  This function generates figures in the specified path folder and returns 0.
#' @export
plot_umap <- function(selected_data, path, verbose = FALSE){

  # Check if the list contains data from UMAPSs.
  if(is.null(selected_data$umap_plot_data)){
    stop("No UMAP data in the list.")
  }

  # Check if path exists; if not then create it.
  if(!is.null(path)){
    if(!dir.exists(path)){
      if(verbose){message(paste("Creating %s folder", path))}
      dir.create(path, recursive = TRUE)
    } else {
      if(verbose){message(paste(path, "folder already exists. Output will be over written."))}
    }
  }


  # Bind global variables.
  UMAP1 <- UMAP2 <- cell_type <- cluster  <- stim_type <- NULL

  # Group data according to clusters and stimulation type.
  group_data <- group_by(selected_data$umap_plot_data, cluster, stim_type)

  # Split groups into a list of individual tables.
  split_groups <- group_split(group_data)

  # Create ggplot for a single group.
  for(i in 1:length(split_groups)){
    clust <- unique(split_groups[[i]]$cluster)
    stim <- unique(split_groups[[i]]$stim_type)
    if(verbose){message(paste("Plotting for the cluster", clust, "and the stim type", stim))}

    umap_plot <- ggplot(split_groups[[i]], aes(x = UMAP1, y = UMAP2, color = cell_type)) +
    geom_point(alpha = 0.25, size = 2) +
    labs(color = "Cell Type", title = paste0("Cluster: ", clust,
                                             "; Stim: ", stim,
                                             "\nTotal No. Cells: ", unique(split_groups[[i]]$tot_of_cells),
                                             "; No. of Cells Plotted: ", unique(split_groups[[i]]$no_of_cells))) +
    scale_x_continuous("UMAP1") +
    scale_y_continuous("UMAP2")

    if(!is.null(path)){
      ggsave(paste0("plot_umap_",clust,"_", stim, ".png"),
             plot = umap_plot, device = "png", path = file.path(path), width = 7, height = 5, dpi = 300)
    }
  }
  return(0)
}



