#' @title SCS Selected Marker Plots Pipeline
#' @description Metafunction to plot all the three types of diagnostic
#'              plots on the data (*.rds files) generated by
#'              \code{scs_selected_markers} function/pipeline.
#'
#' @param original_data       Original tibble/data.frame what was used in \code{\link{scs_selected_markers}} for
#'                            the \code{\link{stim_cell_selector}} function.
#' @param selected_data_path  Path to the folder containing the \code{*.rds} files from
#'                            \code{\link{scs_selected_markers}} function.
#' @param figure_path         Path to the folder where the figures should be saved.
#' @param verbose             Logical. To make function more verbose. Default is FALSE.
#'
#' @return Generates plots in the specified folder and returns 0 upon successfull completion.
#' @export
plots_selected_markers <- function(original_data, selected_data_path, figure_path, verbose = FALSE){
  # For debugging.
  # original_data <- chi11_1k$expr_data
  # selected_data_path <- file.path("/Users/farmerr2/sandbox/devel/niaid/selected_data")
  # figure_path <- file.path("/Users/farmerr2/sandbox/devel/niaid/figures")
  # verbose <- TRUE

  filenames <- Sys.glob(file.path(selected_data_path,"*.rds"))
  for(file in filenames){
    selected_data <- readRDS(file.path(file))

    # Check if the combination has passed the Fisher's exact test.
    if(nrow(selected_data$summary) > 0){

      # Plot stacked bar plots.
      plot_sbp(selected_data, path = file.path(figure_path, "sbp_plots"), verbose = verbose)

      # Plot UMAPs.
      if(selected_data$umap == TRUE){
        plot_umap(selected_data, path = file.path(figure_path, "umap_plots"), verbose = verbose)
      }

      # Plot KDE plots.
      plot_kde(original_data, selected_data, path = file.path(figure_path, "kde_plots"), verbose = verbose)
    }
  }

  return(0)
}
