#' Plot Stacked Bar Plots explaining k-means clustering and Fisher's Exact test
#'
#' @param selected_data     Returned list from the \code{\link{stim_cell_selector}} or
#'                          \code{\link{stim_cell_selector_single_marker}} function.
#' @param path              Path to the folder to save figures generated by this function.
#' @param verbose           Logical. To make function more verbose. Default is FALSE.
#'
#' @return This function generates figures in the specified path folder and returns 0.
#' @export
plot_sbp <- function(selected_data, path, verbose = FALSE){
  # Check if path exists; if not then create it.
  if(!is.null(path)){
    if(!dir.exists(path)){
      if(verbose){message(paste("Creating %s folder", path))}
      dir.create(path, recursive = TRUE)
    } else {
      if(verbose){message(paste(path, "folder already exists. Output will be over written."))}
    }
  }

  # Define colors.
  cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

  # Bind global variables.
  cell_population <- k_cluster <- stim_status <- stim_type <- NULL

  # Group data according to clusters and stimulation type.
  group_data <- group_by(selected_data$stacked_bar_plot_data, cell_population, stim_type)

  # Split groups into a list of individual tables.
  split_groups <- group_split(group_data)

  # Create ggplot for a single group.
  for(i in 1:length(split_groups)){
    clust <- unique(split_groups[[i]]$cell_population)
    stim <- unique(split_groups[[i]]$stim_type)
    if(verbose){message(paste("Plotting for the cell population", clust, "and stimulation", stim))}
    stacked_plot <- ggplot(split_groups[[i]], aes(fill = k_cluster, y=count, x=stim_status)) +
      geom_bar(position="fill", stat="identity") +
      scale_fill_manual(values=cbPalette) +
      labs(title=paste0("Cell Population: ", clust,
                        "; Stimulation: ", stim,
                        "\nFisher's P-value: ", round(unique(split_groups[[i]]$f_p_val),3),
                        "; Stim. Cluster: ",unique(split_groups[[i]]$stim_clust)),
           x ="Stim. Status", y = "Cell Count %", fill = "K-means Cluster")

    if (!is.null(path)) {
      ggsave(
        paste0("plot_sbp_", clust, "_", stim, ".png"),
        plot = stacked_plot,
        device = "png",
        path = file.path(path),
        width = 6,
        height = 4,
        dpi = 300
      )
    }
  }
  return(0)
}




