#' Plot Individual Marker Distribution Before and After Selection
#'
#' @param selected_data    List output of the \code{\link{stim_cell_selector}} function.
#' @param path             Path to the folder to save figures generated by this function.
#' @param verbose          Logical. To make function more verbose. Default is FALSE.
#'
#' @importFrom tidyr gather
#' @importFrom dplyr select filter
#' @import ggplot2
#' @importFrom ggridges geom_density_ridges
#' @return Generates plots in the specified folder and returns 0 upon successfull completion.
#' @export
plot_kde <- function(selected_data, path, verbose = FALSE){
  # Check if path exists; if not then create it.
  if(!is.null(path)){
    if(!dir.exists(path)){
      if(verbose){message(paste("Creating %s folder", path))}
      dir.create(path, recursive = TRUE)
    } else {
      if(verbose){message(paste(path, "folder already exists. Output will be over written."))}
    }
  }

  # Bind global variables.
  cell_population <- stim_type <- distribution <- marker_exp <- k_cluster_id <- responding_cluster <- p.value <- NULL

  # Define colors.
  cbPalette <- c("#E69F00", "#009E73", "#56B4E9", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

  state_markers <- selected_data$state_markers
  cluster_col  <- selected_data$cluster_col

  # Convert the pre k-means data from wide to long form for the state markers.
  # original_data <- original_data[, c(cluster_col, "stim_type", state_markers)]
  original_data <- selected_data$response_mapping_main %>%
    dplyr::select(cell_population, stim_type, all_of(state_markers))
  gather_ori_dat <- data.frame()
  for(state in state_markers){
    temp_df <- original_data %>% dplyr::select(cell_population, stim_type)
    marker_dat <- tidyr::gather(original_data[state], key = "state_marker", value = "marker_exp")
    temp_df <- cbind(temp_df, marker_dat, "distribution" = "stim")
    gather_ori_dat <- rbind(gather_ori_dat, temp_df)
  }
  # gather_ori_dat <- rename(as_tibble(gather_ori_dat), "cluster" = cluster_col)

  # Convert the post k-means data from wide to long form for the state markers.
  selec_data <- selected_data$response_mapping_main %>%
    dplyr::filter(k_cluster_id == responding_cluster & stim_type %in% selected_data$stim_label) %>%
    dplyr::select(cell_population, stim_type, all_of(state_markers))
  # selec_data <- selec_data[, c(cell_population, "stim_type", state_markers)]
  gather_selec_dat <- data.frame()
  for(state in state_markers){
    temp_df <- selec_data %>% dplyr::select(cell_population, stim_type)
    marker_dat <- tidyr::gather(selec_data[state], key = "state_marker", value = "marker_exp")
    temp_df <- cbind(temp_df, marker_dat, "distribution" = "selected")
    gather_selec_dat <- rbind(gather_selec_dat, temp_df)
  }
  # gather_selec_dat <- rename(as_tibble(gather_selec_dat), "cluster" = all_of(cell_population))

  if(length(state_markers) <= 4){
    n_col <- length(state_markers)
    n_row <- 1
  } else if(length(state_markers) > 4){
    n_col <- 4
    n_row_temp <- length(state_markers) / n_col
    if(is.integer(n_row_temp)){
      n_row <- n_row_temp
    } else {
      n_row <- as.integer(n_row_temp) + 1
    }
  }

  comb_f_sig <- selected_data$all_fisher_p_val %>%
    dplyr::filter(p.value < 0.05)
  # summary <- selected_data$summary
  for(i in 1:nrow(comb_f_sig)){
    # Plot KDE of original (pre-k-means clustering) distribution overlaid
    # by the KDE of the k-selected distribution.
    st <- as.character(comb_f_sig[[i,1]])
    cl <- as.character(comb_f_sig[[i,2]])


    clust_stim_k <- gather_selec_dat[gather_selec_dat$cell_population == cl & gather_selec_dat$stim_type == st, ]
    clust_stim_ori <- gather_ori_dat[gather_ori_dat$cell_population == cl & gather_ori_dat$stim_type == st, ]
    clust_unstim_ori <- gather_ori_dat[gather_ori_dat$cell_population == cl & gather_ori_dat$stim_type == selected_data$unstim_label, ]
    clust_unstim_ori$distribution <- "unstim"
    clust_stim <- as_tibble(rbind(clust_stim_k, clust_stim_ori, clust_unstim_ori))

    base_size <- if(n_col >=4){20}else if(n_col < 4){10}
    theme_set(theme_grey(base_size = base_size))
    p <- ggplot(data = clust_stim, aes(x = marker_exp , y = distribution)) +
      ggridges::geom_density_ridges(aes(fill = distribution), scale = 1) +
      scale_fill_manual(values=cbPalette) +
      labs(title = paste0("Cell Population: ", cl, "; Stimulation: ", st),
           x = "Marker Expression",
           y = "Distribution",
           fill = "Distribution")

    kde_plot <- p + facet_wrap( ~ state_marker, nrow = n_row, ncol = n_col)
      #theme(plot.title = element_text(face = "bold"))
    # theme(axis.text.x = element_text( size = 20 ),
      #       axis.text.y = element_text( size = 20 ),
      #       axis.title = element_text( size = 20 ),
      #       strip.text = element_text(size = 20),
      #       legend.text = element_text(size = 20),
      #       legend.title = element_text(size = 20),
      #       plot.title = element_text(size=22, face = "bold"))
    if(!is.null(path)){
      ggsave(paste0("plot_kde_", cl, "_", st, ".png"), plot = kde_plot, device = "png",
           path = path, width = n_col * 4, height = n_row * 3, dpi = 300)
    }
  }

  return(0)
}
